'''
ManualGaitAnalyzer :

@Author : Designed by Kai-Tang T., implemented with the assistance of Gemini AI (and Validated by KT).'

@LastUpdate : 6/24/2026

@UpdateLog:

* 6/23/26 : Uses Gemini AI to create the structure of the code following ideas from KT. Incorporating convertion ratio logic by getting pixel distance and user define real world distance. Takes three points to denote the coordinate and frame of hindpaw movements on each leg to output stride length and speed. Validated the output generated to be similar to the one generated by PrAnCER program. Sanity Check the output falls within expected ranges.

* 6/24/26 : Added the feature to remove the last points (for editing ability for misclicks). Within a folder, save all the different MUID (videos) within the same .csv file, different rows indicating different MUID.

* 7/7/26 : Added Base of Support calculations.

* 7/20/26 : Added a pause after inputting points and require the user the press "ENTER" before moving onto the next step.
'''

import cv2
import numpy as np
import os
import math
import pandas as pd
import tkinter as tk
from tkinter import filedialog
import tkinter.messagebox as tkMessageBox

# Global Variables for Tracking State
clicked_points = []  # Stores the coordinates (spatial) and the specific frame (temporal) of each clicked points.
current_stage = "CALIBRATION"  # Stages: CALIBRATION, HIND_RIGHT, HIND_LEFT, DONE
frame_idx = 0  # Shared the current frame with mouse_callback functions.

# This functions specify that in the event of a mice click, it saves the coordinate and the frame within clicked_points.
def mouse_callback(event, x, y, flags, param):
    global clicked_points, current_stage, frame_idx
    if event == cv2.EVENT_LBUTTONDOWN:
        if current_stage == "CALIBRATION" and len(clicked_points) < 2:
            clicked_points.append((x, y, frame_idx))
            if len(clicked_points) == 2:
                print("Calibration points captured. Press ENTER to confirm real distance.")
        elif current_stage == "HIND_RIGHT" and len(clicked_points) < 5:
            clicked_points.append((x, y, frame_idx))
            print(f"Captured Hind Right Print #{len(clicked_points) - 2} at frame {frame_idx}")
        elif current_stage == "HIND_LEFT" and len(clicked_points) < 8:
            clicked_points.append((x, y, frame_idx))
            print(f"Captured Hind Left Print #{len(clicked_points) - 5} at frame {frame_idx}")


def main():
    global clicked_points, current_stage, frame_idx

    # 1. Select Video File
    root = tk.Tk()
    root.withdraw()
    video_path = filedialog.askopenfilename(title="Select Video File for Manual Analysis")

    if not video_path:
        print("No file selected. Exiting.")
        return

    # Generate the output file name based on the directory/folder that the video is in
    video_dir = os.path.dirname(video_path)
    folder_name = os.path.basename(video_dir)
    output_file = os.path.join(video_dir, f"{folder_name}_EasyGait_Parameter.csv")

    # Obtain the MUID of each video based on the video filename
    video_name = os.path.basename(video_path)
    muid = os.path.splitext(video_name)[0]

    # 2. Extract Native Video Properties
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS) #Get FPS, this is important for the Temporal Parameteres

    if fps <= 0 or math.isnan(fps):
        fps = 30.0

    # Read first frame for calibration
    ret, frame = cap.read()
    if not ret:
        print("Error reading video file.")
        cap.release()
        return

    #Resize the screeen so regardless of the size of the video, it can always be displayed on computer.
    display_w, display_h = 800, 600
    first_frame_resized = cv2.resize(frame, (display_w, display_h))

    # 3. Stage 1: Calibration (Points 1 & 2)
    window_title = f"EasyGait - {video_name}"
    cv2.namedWindow(window_title)
    cv2.setMouseCallback(window_title, mouse_callback)

    tkMessageBox.showinfo("Step 1: Calibration",
                          "Click TWO points to mark a known reference distance.\nPress ENTER to confirm.\nPress 'C' to clear last point.")

    while True:
        img_copy = first_frame_resized.copy()

        # Click two points, each points will display Cal 1 or 2
        for i, pt in enumerate(clicked_points[:2]):
            cv2.circle(img_copy, (pt[0], pt[1]), 5, (0, 0, 255), -1)
            cv2.putText(img_copy, f"Cal {i + 1}", (pt[0] + 8, pt[1] + 5), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 1)

        # Once clicked two points, connect them
        if len(clicked_points) == 2:
            cv2.line(img_copy, (clicked_points[0][0], clicked_points[0][1]),
                     (clicked_points[1][0], clicked_points[1][1]), (0, 255, 0), 2)

        cv2.imshow(window_title, img_copy)
        key = cv2.waitKey(30) & 0xFF

        # Once two points are clicked and press enter, finish the Calibration settings
        if key == 13 and len(clicked_points) == 2:  # ENTER
            break
        # If press the button C regardless of capitalization, it can undo the last point
        elif key == ord('c') or key == ord('C'):
            if len(clicked_points) > 0:
                clicked_points.pop()
                print("Last calibration point removed.")

    # Calculate Pixel Distance between the two points.
    (cx1, cy1, _), (cx2, cy2, _) = clicked_points[0], clicked_points[1]
    pixel_distance = math.sqrt((cx2 - cx1) ** 2 + (cy2 - cy1) ** 2)

    # Prompt user for real world distance of the drawn scale
    from tkinter import simpledialog
    real_distance_cm = simpledialog.askfloat("Calibration Scale", "Enter real-world distance in cm:", minvalue=0.001)

    if real_distance_cm is None or real_distance_cm <= 0:
        print("Invalid calibration. Exiting.")
        cv2.destroyAllWindows()
        cap.release()
        return

    # Calculate the convertion ratio between Pixel Distance and Real Distance. With this calibration
    # Any data generated in pixel distance can multiply this conversion ratio to output real world distance (cm).
    cm_per_pixel = (real_distance_cm / pixel_distance)
    print(f"Calibration Set: {cm_per_pixel:.5f} cm/pixel | Video Framerate: {fps:.2f} FPS")

    # 4. Interactive Gait Video Player Settings
    current_stage = "HIND_RIGHT"
    tkMessageBox.showinfo("Step 2: Track Path",
                          "Use trackbar to navigate time.\nPress SPACEBAR to Pause/Play.\nClick 3 consecutive Hind Right steps.\nPress 'C' to Undo last point.")

    frame_idx = 0
    is_playing = True
    playback_speed = 100
    cv2.createTrackbar("Timeline", window_title, 0, total_frames - 1, lambda val: None)

    # 5. Continuous Slow Motion Playback Loop
    while current_stage != "DONE":
        trackbar_pos = cv2.getTrackbarPos("Timeline", window_title)
        if not is_playing:
            frame_idx = trackbar_pos
        else:
            cv2.setTrackbarPos("Timeline", window_title, frame_idx)

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()

        # Looping logic if end of video is reached
        if not ret:
            frame_idx = 0
            cv2.setTrackbarPos("Timeline", window_title, frame_idx)
            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
            ret, frame = cap.read()
            if not ret:
                print("Error looping video file.")
                break

        frame_resized = cv2.resize(frame, (display_w, display_h))

        cv2.putText(frame_resized, f"Stage: Click 3 {current_stage.replace('_', ' ')} Points", (15, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        cv2.putText(frame_resized, f"Frame: {frame_idx} / {total_frames - 1} | [Space]: Pause | [C]: Undo", (15, 55),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.4, (200, 200, 200), 1)

        # Drawing of the paws. 3rd, 4th, 5th clicked point denote the location of the right paws. Draw a line connecting them.
        if len(clicked_points) >= 3:
            for j in range(2, min(len(clicked_points), 5)):
                pt = clicked_points[j]
                cv2.circle(frame_resized, (pt[0], pt[1]), 6, (255, 191, 0), -1)
                cv2.putText(frame_resized, f"R{j - 1}", (pt[0] + 8, pt[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                            (255, 191, 0), 2)
            if len(clicked_points) >= 4:
                cv2.line(frame_resized, (clicked_points[2][0], clicked_points[2][1]),
                         (clicked_points[3][0], clicked_points[3][1]), (255, 191, 0), 2)
            if len(clicked_points) >= 5:
                cv2.line(frame_resized, (clicked_points[3][0], clicked_points[3][1]),
                         (clicked_points[4][0], clicked_points[4][1]), (255, 191, 0), 2)

        # Drawing of the paws. 6th, 7th, 8th clicked point denote the location of the left paws. Draw a line connecting them.
        if len(clicked_points) >= 6:
            for k in range(5, min(len(clicked_points), 8)):
                pt = clicked_points[k]
                cv2.circle(frame_resized, (pt[0], pt[1]), 6, (0, 69, 255), -1)
                cv2.putText(frame_resized, f"L{k - 4}", (pt[0] + 8, pt[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 69, 255),
                            2)
            if len(clicked_points) >= 7:
                cv2.line(frame_resized, (clicked_points[5][0], clicked_points[5][1]),
                         (clicked_points[6][0], clicked_points[6][1]), (0, 69, 255), 2)
            if len(clicked_points) >= 8:
                cv2.line(frame_resized, (clicked_points[6][0], clicked_points[6][1]),
                         (clicked_points[7][0], clicked_points[7][1]), (0, 69, 255), 2)

        cv2.imshow(window_title, frame_resized)

        # User key functions. Space pause the video, enter just finish calculation, C undo the last point.
        key = cv2.waitKey(playback_speed if is_playing else 30) & 0xFF
        if key == 32:  # SPACEBAR
            is_playing = not is_playing
        elif key == 13:  # ENTER
            if current_stage == "HIND_RIGHT" and len(clicked_points) == 5:
                current_stage = "HIND_LEFT"
                tkMessageBox.showinfo("Step 3: Track Hind Left",
                                      "Hind Right registered manually.\nNow click 3 consecutive Hind Left steps.")
            elif current_stage == "HIND_LEFT" and len(clicked_points) == 8:
                current_stage = "DONE"
                tkMessageBox.showinfo("Step 4: Confirm Data", 
                                      "Hind Left registered.\nPress ENTER one more time to calculate metrics and save.")
            elif current_stage == "DONE":
                break
        elif key == ord('c') or key == ord('C'):  # Undo functionality
            if len(clicked_points) > 2:  # Do not delete calibration points here
                popped = clicked_points.pop()
                print(f"Removed last tracked point. Total points: {len(clicked_points)}")
                # Reset tracking stage if rolled back
                if len(clicked_points) < 5:
                    current_stage = "HIND_RIGHT"
        elif key == 27:  # ESC. End the program does not output anything.
            cv2.destroyAllWindows()
            cap.release()
            return

        if is_playing:
            frame_idx += 1
            if frame_idx >= total_frames:
                frame_idx = 0  # Force loop restart index initialization

    cv2.destroyAllWindows()
    cap.release()

    # 6. Complete Mathematical & Structural Row Output System
    if len(clicked_points) == 8:
        p3, p4, p5 = clicked_points[2], clicked_points[3], clicked_points[4]
        p6, p7, p8 = clicked_points[5], clicked_points[6], clicked_points[7]

        # Base of Support (BOS) Calculations (Simplified Y-Axis Only)
        px_bos1 = abs(p6[1] - p3[1])  
        px_bos2 = abs(p7[1] - p4[1])  
        px_bos3 = abs(p8[1] - p5[1])  

        # Spatial Pixel Calculations. (x2-x1, y2-y1)
        px_r1 = math.hypot(p4[0] - p3[0], p4[1] - p3[1])
        px_r2 = math.hypot(p5[0] - p4[0], p5[1] - p4[1])
        px_l1 = math.hypot(p7[0] - p6[0], p7[1] - p6[1])
        px_l2 = math.hypot(p8[0] - p7[0], p8[1] - p7[1])

        # Temporal Frame Deltas (Frame2-Frame1)
        f_r1 = abs(p4[2] - p3[2])
        f_r2 = abs(p5[2] - p4[2])
        f_l1 = abs(p7[2] - p6[2])
        f_l2 = abs(p8[2] - p7[2])

        # Convert temporal computer metric (Frame) to real world metric (Seconds).
        t_r1 = f_r1 / fps
        t_r2 = f_r2 / fps
        t_l1 = f_l1 / fps
        t_l2 = f_l2 / fps

        # Convert Spacial computer metric (Pixel Distance) to real world metric (Cm).
        # Base of Support
        cm_bos1 = px_bos1 * cm_per_pixel
        cm_bos2 = px_bos2 * cm_per_pixel
        cm_bos3 = px_bos3 * cm_per_pixel
        # Stride Length
        cm_r1 = px_r1 * cm_per_pixel
        cm_r2 = px_r2 * cm_per_pixel
        cm_l1 = px_l1 * cm_per_pixel
        cm_l2 = px_l2 * cm_per_pixel
        

        # Velocity tracking computations
        sp_r1 = cm_r1 / t_r1 if t_r1 > 0 else 0
        sp_r2 = cm_r2 / t_r2 if t_r2 > 0 else 0
        sp_l1 = cm_l1 / t_l1 if t_l1 > 0 else 0
        sp_l2 = cm_l2 / t_l2 if t_l2 > 0 else 0

        # Calculate Spatial Mean for Base of Support
        cm_bos_avg = (cm_bos1 + cm_bos2 + cm_bos3) / 3.0

        # Calculate Spatial Mean for right, left, and overall average stride length
        cm_r_avg = (cm_r1 + cm_r2) / 2.0
        cm_l_avg = (cm_l1 + cm_l2) / 2.0
        cm_overall_avg = (cm_r1 + cm_r2 + cm_l1 + cm_l2) / 4.0


        # Calculate the temporal mean for stride duration and speed.
        t_overall_avg = (t_r1 + t_r2 + t_l1 + t_l2) / 4.0
        sp_overall_avg = (sp_r1 + sp_r2 + sp_l1 + sp_l2) / 4.0

        # Formulate metrics row array using video filename as MUID
        new_row = {
            'MUID': [str(muid)],
            'Base of Support (cm)': [cm_bos_avg],
            'Average Stride (cm)': [cm_overall_avg],
            'Right Avg Stride (cm)': [cm_r_avg],
            'Left Avg Stride (cm)': [cm_l_avg],
            'AvgStride Duration (second)': [t_overall_avg],
            'Avg Stride Speed (cm / second)': [sp_overall_avg]
        }
        new_df = pd.DataFrame(new_row)

        # File Handling Logic: Check file existence, verify MUID status, rewrite or append
        if os.path.exists(output_file):
            try:
                existing_df = pd.read_csv(output_file)
                # Drop existing row matching MUID if present to enable a safe rewrite sequence
                if 'MUID' in existing_df.columns:
                    existing_df = existing_df[existing_df['MUID'].astype(str) != str(muid)]

                final_df = pd.concat([existing_df, new_df], ignore_index=True)
            except Exception as e:
                print(f"Error checking file, fallback to initialization pattern: {e}")
                final_df = new_df
        else:
            final_df = new_df

        # Save to localized disk location
        final_df.to_csv(output_file, index=False)
        print(f"\nAnalysis Saved Successfully to: {output_file}")
        tkMessageBox.showinfo("Success", f"Metrics updated for MUID (Video): {muid}\nFile Location: {output_file}")


if __name__ == '__main__':
    main()